import string

bad_list = ['2g1c', '2girls1cup', '4r5e', '5h1t', '5hit', 'a2m', 'a55hole', 'a_s_s', 'acrotomophilia', 'aeolus', 'ahole',
           'alabamahotpocket', 'alaskanpipeline', 'anal', 'analimpaler', 'analleakage', 'analprobe', 'anilingus', 'anus',
           'apeshit', 'ar5e', 'areola', 'areole', 'arian', 'arrse', 'arse', 'arsehole', 'aryan', 'ass', 'ass-fucker', 'ass-hat',
           'ass-jabber', 'ass-pirate', 'assbag', 'assbandit', 'assbang', 'assbanged', 'assbanger', 'assbangs', 'assbite',
           'assclown', 'asscock', 'asscracker', 'asses', 'assface', 'assfaces', 'assfuck', 'assfucker', 'assfukka', 'assgoblin',
           'assh0le', 'asshat', 'asshead', 'assho1e', 'asshole', 'assholes', 'asshopper', 'assjacker', 'asslick', 'asslicker',
           'assmaster', 'assmonkey', 'assmucus', 'assmunch', 'assmuncher', 'assnigger', 'asspirate', 'assshit', 'assshole',
           'asssucker', 'asswad', 'asswhole', 'asswipe', 'asswipes', 'autoerotic', 'axwound', 'azazel', 'azz', 'b00bs', 'b17ch',
           'b1tch', 'babeland', 'babybatter', 'babyjuice', 'ballbag', 'ballgag', 'ballgravy', 'ballkicking', 'balllicking',
           'balls', 'ballsack', 'ballsucking', 'bampot', 'bangbros', 'bareback', 'barelylegal', 'barenaked', 'barf', 'bastard',
           'bastardo', 'bastards', 'bastinado', 'battyboy', 'bawdy', 'bbw', 'bdsm', 'beaner', 'beaners', 'beardedclam', 'beastial',
           'beastiality', 'beatch', 'beaver', 'beavercleaver', 'beaverlips', 'beefcurtain', 'beefcurtains', 'beeyotch', 'bellend',
           'bender', 'beotch', 'bescumber', 'bestial', 'bestiality', 'biatch', 'bigblack', 'bigbreasts', 'bigknockers', 'bigtits',
           'bimbo', 'bimbos', 'bint', 'birdlock', 'bitch', 'bitchass', 'bitched', 'bitcher', 'bitchers', 'bitches', 'bitchin',
           'bitching', 'bitchtit', 'bitchtits', 'bitchy', 'blackcock', 'blondeaction', 'blondeonblondeaction', 'bloodclaat',
           'bloody', 'bloodyhell', 'blowjob', 'blowjobs', 'blowme', 'blowmud', 'blowyourload', 'bluewaffle', 'blumpkin', 'bod',
           'bodily', 'boink', 'boiolas', 'bollock', 'bollocks', 'bollok', 'bollox', 'bondage', 'boned', 'boner', 'boners', 'bong',
           'boob', 'boobies', 'boobs', 'booby', 'booger', 'bookie', 'boong', 'booobs', 'boooobs', 'booooobs', 'booooooobs',
           'bootee', 'bootie', 'booty', 'bootycall', 'booze', 'boozer', 'boozy', 'bosom', 'bosomy', 'breasts', 'breeder',
           'brotherfucker', 'brownshowers', 'brunetteaction', 'buceta', 'bugger', 'bukkake', 'bulldyke', 'bulletvibe', 'bullshit',
           'bullshits', 'bullshitted', 'bullturds', 'bum', 'bumblefuck', 'bumboy', 'bumclat', 'bummer', 'buncombe', 'bung',
           'bunghole', 'bunnyfucker', 'bustaload', 'busty', 'butt', 'butt-pirate', 'buttcheeks', 'buttfuck', 'buttfucka',
           'buttfucker', 'butthole', 'buttmuch', 'buttmunch', 'buttplug', 'c-0-c-k', 'c-o-c-k', 'c-u-n-t', 'c0ck', 'c0cksucker',
           'caca', 'cacafuego', 'cahone', 'cameltoe', 'camgirl', 'camslut', 'camwhore', 'carpetmuncher', 'cawk', 'cervix',
           'chesticle', 'chi-chiman', 'chickwithadick', 'child-fucker', 'chinc', 'chincs', 'chink', 'chinky', 'choad', 'choade',
           'chocice', 'chocolaterosebuds', 'chode', 'chodes', 'chotabags', 'cipa', 'circlejerk', 'cl1t', 'clevelandsteamer',
           'climax', 'clit', 'clitface', 'clitfuck', 'clitlicker', 'clitoris', 'clitorus', 'clits', 'clitty', 'clittylitter',
           'cloverclamps', 'clunge', 'clusterfuck', 'cnut', 'cocain', 'cocaine', 'coccydynia', 'cock', 'cock-sucker', 'cockass',
           'cockbite', 'cockblock', 'cockburger', 'cockeye', 'cockface', 'cockfucker', 'cockhead', 'cockholster', 'cockjockey',
           'cockknocker', 'cockknoker', 'cocklump', 'cockmaster', 'cockmongler', 'cockmongruel', 'cockmonkey', 'cockmunch',
           'cockmuncher', 'cocknose', 'cocknugget', 'cockpocket', 'cocks', 'cockshit', 'cocksmith', 'cocksmoke', 'cocksmoker',
           'cocksniffer', 'cocksnot', 'cocksuck', 'cocksucked', 'cocksucker', 'cocksuckers', 'cocksucking', 'cocksucks',
           'cocksuka', 'cocksukka', 'cockwaffle', 'coffindodger', 'coital', 'cok', 'cokmuncher', 'coksucka', 'commie', 'condom',
           'coochie', 'coochy', 'coon', 'coonnass', 'coons', 'cooter', 'coprolagnia', 'coprophilia', 'copsomewood', 'corksucker',
           'cornhole', 'corpulent', 'corpwhore', 'cox', 'crabs', 'crack', 'cracker', 'crackwhore', 'crap', 'crappy', 'creampie',
           'cretin', 'crikey', 'cripple', 'crotte', 'cum', 'cumbubble', 'cumchugger', 'cumdump', 'cumdumpster', 'cumfreak',
           'cumguzzler', 'cumjockey', 'cummer', 'cummin', 'cumming', 'cums', 'cumshot', 'cumshots', 'cumslut', 'cumstain',
           'cumtart', 'cunilingus', 'cunillingus', 'cunnie', 'cunnilingus', 'cunny', 'cunt', 'cunt-struck', 'cuntass', 'cuntbag',
           'cuntface', 'cunthair', 'cunthole', 'cunthunter', 'cuntlick', 'cuntlicker', 'cuntlicking', 'cuntrag', 'cunts',
           'cuntsicle', 'cuntslut', 'cus', 'cutrope', 'cyalis', 'cyberfuc', 'cyberfuck', 'cyberfucked', 'cyberfucker',
           'cyberfuckers', 'cyberfucking', 'd0ng', 'd0uch3', 'd0uche', 'd1ck', 'd1ld0', 'd1ldo', 'dago', 'dagos', 'dammit', 'damn',
           'damned', 'damnit', 'darkie', 'darn', 'daterape', 'dawgie-style', 'deepthroat', 'deggo', 'dendrophilia', 'dick',
           'dick-ish', 'dick-sneeze', 'dickbag', 'dickbeaters', 'dickdipper', 'dickface', 'dickflipper', 'dickfuck', 'dickfucker',
           'dickhead', 'dickheads', 'dickhole', 'dickish', 'dickjuice', 'dickmilk', 'dickmonger', 'dickripper', 'dicks', 'dickshy',
           'dicksipper', 'dickslap', 'dicksucker', 'dicksucking', 'dicktickler', 'dickwad', 'dickweasel', 'dickweed',
           'dickwhipper', 'dickwod', 'dickzipper', 'diddle', 'dike', 'dildo', 'dildos', 'diligaf', 'dillweed', 'dimwit', 'dingle',
           'dingleberries', 'dingleberry', 'dink', 'dinks', 'dipship', 'dipshit', 'dirsa', 'dirty', 'dirtypillows', 'dirtysanchez',
           'div', 'dlck', 'dog-fucker', 'doggie-style', 'doggiestyle', 'doggin', 'dogging', 'doggy-style', 'doggystyle',
           'dogstyle', 'dolcett', 'domination', 'dominatrix', 'dommes', 'dong', 'donkeypunch', 'donkeyribber', 'doochbag',
           'doofus', 'dookie', 'doosh', 'dopey', 'doubledong', 'doublelift', 'doublepenetration', 'douch3', 'douche', 'douche-fag',
           'douchebag', 'douchebags', 'douchewaffle', 'douchey', 'dpaction', 'drunk', 'dryhump', 'duche', 'dumass', 'dumbass',
           'dumbasses', 'dumbcunt', 'dumbfuck', 'dumbshit', 'dummy', 'dumshit', 'dvda', 'dyke', 'dykes', 'eatadick', 'eathairpie',
           'eatmyass', 'ecchi', 'ejaculate', 'ejaculated', 'ejaculates', 'ejaculating', 'ejaculatings', 'ejaculation', 'ejakulate',
           'erect', 'erection', 'erotic', 'erotism', 'escort', 'essohbee', 'eunuch', 'extacy', 'extasy', 'f-u-c-k', 'f4nny',
           'f_u_c_kf', 'facial', 'fack', 'fag', 'fagbag', 'fagfucker', 'fagg', 'fagged', 'fagging', 'faggit', 'faggitt', 'faggot',
           'faggotcock', 'faggots', 'faggs', 'fagot', 'fagots', 'fags', 'fagtard', 'faig', 'faigt', 'fanny', 'fannybandit',
           'fannyflaps', 'fannyfucker', 'fanyy', 'fart', 'fartknocker', 'fatass', 'fcuk', 'fcuker', 'fcuking', 'fecal', 'feck',
           'fecker', 'feist', 'felch', 'felcher', 'felching', 'fellate', 'fellatio', 'feltch', 'feltcher', 'femalesquirting',
           'femdom', 'fenian', 'fice', 'figging', 'fingerbang', 'fingerfuck', 'fingerfucked', 'fingerfucker', 'fingerfuckers',
           'fingerfucking', 'fingerfucks', 'fingering', 'fisted', 'fistfuck', 'fistfucked', 'fistfucker', 'fistfuckers',
           'fistfucking', 'fistfuckings', 'fistfucks', 'fisting', 'fisty', 'flamer', 'flange', 'flaps', 'fleshflute', 'flogthelog',
           'floozy', 'foad', 'foah', 'fondle', 'foobar', 'fook', 'fooker', 'footfetish', 'footjob', 'foreskin', 'freex',
           'frenchify', 'frigg', 'frigga', 'frotting', 'fubar', 'fuc', 'fuck', 'fuck-ass', 'fuck-bitch', 'fuck-tard', 'fucka',
           'fuckass', 'fuckbag', 'fuckboy', 'fuckbrain', 'fuckbutt', 'fuckbutter', 'fuckbuttons', 'fucked', 'fuckedup', 'fucker',
           'fuckers', 'fuckersucker', 'fuckface', 'fuckhead', 'fuckheads', 'fuckhole', 'fuckin', 'fucking', 'fuckings',
           'fuckingshitmotherfucker', 'fuckme', 'fuckmeat', 'fucknugget', 'fucknut', 'fucknutt', 'fuckoff', 'fuckpuppet', 'fucks',
           'fuckstick', 'fucktard', 'fucktards', 'fucktart', 'fucktoy', 'fucktrophy', 'fucktwat', 'fuckup', 'fuckwad', 'fuckwhit',
           'fuckwit', 'fuckwitt', 'fuckyomama', 'fuckyou', 'fudge-packer', 'fudgepacker', 'fuk', 'fuker', 'fukker', 'fukkers',
           'fukkin', 'fuks', 'fukwhit', 'fukwit', 'fuq', 'futanari', 'fux', 'fux0r', 'fvck', 'fxck', 'g-spot', 'gae', 'gai',
           'gang-bang', 'gangbang', 'gangbanged', 'gangbangs', 'ganja', 'gash', 'gassyass', 'gay', 'gayass', 'gaybob', 'gaydo',
           'gayfuck', 'gayfuckist', 'gaylord', 'gays', 'gaysex', 'gaytard', 'gaywad', 'genderbender', 'genitals', 'gey', 'gfy',
           'ghay', 'ghey', 'giantcock', 'gigolo', 'ginger', 'gippo', 'girlon', 'girlontop', 'girlsgonewild', 'git', 'glans',
           'goatcx', 'goatse', 'god', 'god-dam', 'god-damned', 'godamn', 'godamnit', 'goddam', 'goddammit', 'goddamn', 'goddamned',
           'goddamnit', 'godsdamn', 'gokkun', 'goldenshower', 'golliwog', 'gonad', 'gonads', 'gooch', 'goodpoop', 'googirl',
           'gook', 'gooks', 'goregasm', 'gringo', 'grope', 'groupsex', 'gspot', 'gtfo', 'guido', 'guro', 'h0m0', 'h0mo', 'hamflap',
           'handjob', 'hardcore', 'hardcoresex', 'hardon', 'he-she', 'he11', 'hebe', 'heeb', 'hell', 'hemp', 'hentai', 'heroin',
           'herp', 'herpes', 'herpy', 'heshe', 'hircismus', 'hitler', 'hiv', 'ho', 'hoar', 'hoare', 'hobag', 'hoe', 'hoer',
           'holyshit', 'hom0', 'homey', 'homo', 'homodumbshit', 'homoerotic', 'homoey', 'honkey', 'honky', 'hooch', 'hookah',
           'hooker', 'hoor', 'hootch', 'hooter', 'hooters', 'hore', 'horniest', 'horny', 'hotcarl', 'hotchick', 'hotsex',
           'howtokill', 'howtomurdep', 'howtomurder', 'hugefat', 'hump', 'humped', 'humping', 'hun', 'hussy', 'hymen', 'iap',
           'iberianslap', 'inbred', 'incest', 'injun', 'intercourse', 'jack-off', 'jackass', 'jackasses', 'jackhole', 'jackoff',
           'jaggi', 'jagoff', 'jailbait', 'jap', 'japs', 'jellydonut', 'jerk', 'jerk-off', 'jerk0ff', 'jerkass', 'jerked',
           'jerkoff', 'jigaboo', 'jiggaboo', 'jiggerboo', 'jism', 'jiz', 'jizm', 'jizz', 'jizzed', 'jock', 'juggs', 'junglebunny',
           'junkie', 'junky', 'kafir', 'kawk', 'kike', 'kikes', 'kill', 'kinbaku', 'kinkster', 'kinky', 'klan', 'knob', 'knobbing',
           'knobead', 'knobed', 'knobend', 'knobhead', 'knobjocky', 'knobjokey', 'kock', 'kondum', 'kondums', 'kooch', 'kooches',
           'kootch', 'kraut', 'kum', 'kummer', 'kumming', 'kums', 'kunilingus', 'kunja', 'kunt', 'kwif', 'kyke', 'l3itch', 'labia',
           'lameass', 'lardass', 'leatherrestraint', 'leatherstraightjacket', 'lech', 'lemonparty', 'len', 'leper', 'lesbian',
           'lesbians', 'lesbo', 'lesbos', 'lez', 'lezzie', 'lmao', 'lmfao', 'loin', 'loins', 'lolita', 'looney', 'lovemaking',
           'lube', 'lust', 'lusting', 'lusty', 'm-fucking', 'm0f0', 'm0fo', 'm45terbate', 'ma5terb8', 'ma5terbate', 'mafugly',
           'makemecome', 'malesquirting', 'mams', 'masochist', 'massa', 'master-bate', 'masterb8', 'masterbat', 'masterbat3',
           'masterbate', 'masterbating', 'masterbation', 'masterbations', 'masturbate', 'masturbating', 'masturbation', 'maxi',
           'mcfagget', 'menageatrois', 'menses', 'menstruate', 'menstruation', 'meth', 'mick', 'microphallus', 'middlefinger',
           'midget', 'milf', 'minge', 'minger', 'missionaryposition', 'mo-fo', 'mof0', 'mofo', 'molest', 'mong', 'moolie',
           'moomoofoofoo', 'moron', 'mothafuck', 'mothafucka', 'mothafuckas', 'mothafuckaz', 'mothafucked', 'mothafucker',
           'mothafuckers', 'mothafuckin', 'mothafucking', 'mothafuckings', 'mothafucks', 'motherfuck', 'motherfucka',
           'motherfucked', 'motherfucker', 'motherfuckers', 'motherfuckin', 'motherfucking', 'motherfuckings', 'motherfuckka',
           'motherfucks', 'moundofvenus', 'mrhands', 'muff', 'muffdiver', 'muffdiving', 'muffpuff', 'munging', 'munter', 'murder',
           'mutha', 'muthafecker', 'muthafuckker', 'muther', 'mutherfucker', 'n1gga', 'n1gger', 'naked', 'nambla', 'napalm',
           'nappy', 'nawashi', 'nazi', 'nazism', 'needthedick', 'negro', 'neonazi', 'nig-nog', 'nigaboo', 'nigg3r', 'nigg4h',
           'nigga', 'niggah', 'niggas', 'niggaz', 'nigger', 'niggers', 'niggle', 'niglet', 'nignog', 'nimphomania', 'nimrod',
           'ninny', 'ninnyhammer', 'nipple', 'nipples', 'nob', 'nobhead', 'nobjocky', 'nobjokey', 'nonce', 'nsfwimages', 'nude',
           'nudity', 'numbnuts', 'nutbutter', 'nutsack', 'nutter', 'nympho', 'nymphomania', 'octopussy', 'oldbag', 'omg',
           'omorashi', 'onecuptwogirls', 'oneguyonejar', 'opiate', 'opium', 'orally', 'organ', 'orgasim', 'orgasims', 'orgasm',
           'orgasmic', 'orgasms', 'orgies', 'orgy', 'ovary', 'ovum', 'ovums', 'p0rn', 'paedophile', 'paki', 'panooch', 'pansy',
           'pantie', 'panties', 'panty', 'pawn', 'pcp', 'pecker', 'peckerhead', 'pedo', 'pedobear', 'pedophile', 'pedophilia',
           'pedophiliac', 'pee', 'peepee', 'pegging', 'penetrate', 'penetration', 'penial', 'penile', 'penis', 'penisbanger',
           'penisfucker', 'penispuffer', 'perversion', 'phallic', 'phonesex', 'phuck', 'phuk', 'phuked', 'phuking', 'phukked',
           'phukking', 'phuks', 'phuq', 'pieceofshit', 'pigfucker', 'pikey', 'pillowbiter', 'pimp', 'pimpis', 'pinko', 'piss',
           'piss-off', 'pissed', 'pissedoff', 'pisser', 'pissers', 'pisses', 'pissflaps', 'pissin', 'pissing', 'pissoff',
           'pisspig', 'playboy', 'pleasurechest', 'pms', 'polack', 'polesmoker', 'pollock', 'ponyplay', 'poof', 'poon', 'poonani',
           'poonany', 'poontang', 'poop', 'poopchute', 'poopuncher', 'porchmonkey', 'porn', 'porno', 'pornography', 'pornos',
           'pot', 'potty', 'prick', 'pricks', 'prickteaser', 'prig', 'princealbertpiercing', 'prod', 'pron', 'prostitute', 'prude',
           'psycho', 'pthc', 'pube', 'pubes', 'pubic', 'pubis', 'punani', 'punanny', 'punany', 'punkass', 'punky', 'punta', 'puss',
           'pusse', 'pussi', 'pussies', 'pussy', 'pussyfart', 'pussylicking', 'pussypalace', 'pussypounder', 'pussys', 'pust',
           'puto', 'queaf', 'queef', 'queer', 'queerbait', 'queerhole', 'queero', 'queers', 'quicky', 'quim', 'r-tard', 'racy',
           'raghead', 'ragingboner', 'rape', 'raped', 'raper', 'rapey', 'raping', 'rapist', 'raunch', 'rectal', 'rectum', 'rectus',
           'reefer', 'reetard', 'reich', 'renob', 'retard', 'retarded', 'reversecowgirl', 'revue', 'rimjaw', 'rimjob', 'rimming',
           'ritard', 'rosypalm', 'rosypalmandher5sisters', 'rtard', 'rubbish', 'rum', 'rump', 'rumprammer', 'ruski',
           'rustytrombone', 's-h-1-t', 's-h-i-t', 's-o-b', 's0b', 's_h_i_t', 'sadism', 'sadist', 'sambo', 'sandbar', 'sandler',
           'sandnigger', 'sanger', 'santorum', 'sausagequeen', 'scag', 'scantily', 'scat', 'schizo', 'schlong', 'scissoring',
           'screw', 'screwed', 'screwing', 'scroat', 'scrog', 'scrot', 'scrote', 'scrotum', 'scrud', 'scum', 'seaman', 'seamen',
           'seduce', 'seks', 'semen', 'sex', 'sexo', 'sexual', 'sexy', 'sh1t', 'shag', 'shagger', 'shaggin', 'shagging',
           'shamedame', 'shavedbeaver', 'shavedpussy', 'shemale', 'shibari', 'shirtlifter', 'shit', 'shitass', 'shitbag',
           'shitbagger', 'shitblimp', 'shitbrains', 'shitbreath', 'shitcanned', 'shitcunt', 'shitdick', 'shite', 'shiteater',
           'shited', 'shitey', 'shitface', 'shitfaced', 'shitfuck', 'shitfucker', 'shitfull', 'shithead', 'shitheads', 'shithole',
           'shithouse', 'shiting', 'shitings', 'shits', 'shitspitter', 'shitstain', 'shitt', 'shitted', 'shitter', 'shitters',
           'shittier', 'shittiest', 'shitting', 'shittings', 'shitty', 'shiz', 'shiznit', 'shota', 'shrimping', 'sissy', 'skag',
           'skank', 'skeet', 'skullfuck', 'slag', 'slanteye', 'slave', 'sleaze', 'sleazy', 'slope', 'slut', 'slutbag',
           'slutbucket', 'slutdumper', 'slutkiss', 'sluts', 'smartass', 'smartasses', 'smeg', 'smegma', 'smut', 'smutty', 'snatch',
           'sniper', 'snowballing', 'snuff', 'sodoff', 'sodom', 'sodomize', 'sodomy', 'son-of-a-bitch', 'sonofabitch',
           'sonofamotherlessgoat', 'sonofawhore', 'souse', 'soused', 'spac', 'spade', 'sperm', 'spic', 'spick', 'spik', 'spiks',
           'splooge', 'sploogemoose', 'spooge', 'spook', 'spreadlegs', 'spunk', 'stfu', 'stiffy', 'stoned', 'strapon', 'strappado',
           'strip', 'stripclub', 'stroke', 'stupid', 'styledoggy', 'suck', 'suckass', 'sucked', 'sucking', 'sucks', 'suicidegirls',
           'sultrywomen', 'sumofabiatch', 'swastika', 'swinger', 't1t', 't1tt1e5', 't1tties', 'taff', 'taig', 'taintedlove',
           'takingthepiss', 'tampon', 'tard', 'tart', 'tastemy', 'tawdry', 'teabagging', 'teat', 'teets', 'teez', 'teste',
           'testee', 'testes', 'testical', 'testicle', 'testis', 'threesome', 'throating', 'thrust', 'thug', 'thundercunt',
           'tiedup', 'tightwhite', 'tinkle', 'tit', 'titfuck', 'titi', 'tities', 'tits', 'titt', 'tittie5', 'tittiefucker',
           'titties', 'titty', 'tittyfuck', 'tittyfucker', 'tittywank', 'titwank', 'toke', 'tongueina', 'toots', 'topless',
           'tosser', 'towelhead', 'tramp', 'tranny', 'transsexual', 'trashy', 'tribadism', 'trumped', 'tubgirl', 'turd', 'tush',
           'tushy', 'tw4t', 'twat', 'twathead', 'twatlips', 'twats', 'twatty', 'twatwaffle', 'twink', 'twinkie', 'twofingers',
           'twofingerswithtongue', 'twogirlsonecup', 'twunt', 'twunter', 'ugly', 'unclefucker', 'undies', 'undressing', 'unwed',
           'upskirt', 'urethraplay', 'urinal', 'urine', 'urophilia', 'uterus', 'uzi', 'v14gra', 'v1gra', 'va-j-j', 'vag', 'vagina',
           'vajayjay', 'valium', 'venusmound', 'veqtable', 'viagra', 'vibrator', 'violetwand', 'virgin', 'vixen', 'vjayjay',
           'vodka', 'vomit', 'vorarephilia', 'voyeur', 'vulgar', 'vulva', 'w00se', 'wad', 'wang', 'wank', 'wanker', 'wankjob',
           'wanky', 'wazoo', 'wedgie', 'weed', 'weenie', 'weewee', 'weiner', 'weirdo', 'wench', 'wetback', 'wetdream', 'wh0re',
           'wh0reface', 'whitepower', 'whiz', 'whoar', 'whoralicious', 'whore', 'whorealicious', 'whorebag', 'whored', 'whoreface',
           'whorehopper', 'whorehouse', 'whores', 'whoring', 'wigger', 'willies', 'willy', 'windowlicker', 'wiseass', 'wiseasses',
           'wog', 'womb', 'wop', 'wrappingmen', 'wrinkledstarfish', 'wtf', 'x-rated', 'xrated', 'xx', 'xxx', 'yaoi', 'yeasty',
           'yellowshowers', 'yid', 'yiffy', 'yobbo', 'zibbi', 'zoophilia', 'zubb', 'анус', 'аборт', 'бздун', 'беспезды', 'бздюх',
           'бля', 'блудилище', 'блядво', 'блядеха', 'блядина', 'блядистка', 'блядище', 'блядки', 'блядование', 'блядовать', 'блядовитый',
           'блядовозка', 'блядолиз', 'блядоход', 'блядский', 'блядство', 'блядствовать', 'блядун', 'блядь', 'бляди', 'бляд', 'блядюга',
           'блядюра', 'блядюшка', 'блядюшник', 'бордель', 'вагина', 'вафлист', 'вжопить', 'вжопиться', 'вздрачивание', 'вздрачивать',
           'вздрачиваться', 'вздрочить', 'вздрочиться', 'вздрючить', 'вздрючивание', 'вздрючивать', 'взъебка', 'взъебщик', 'взъебнуть',
           'вислозадая', 'влагалище', 'вхуйнуть', 'вхуйнуться', 'вхуякать', 'вхуякаться', 'вхуя', 'вхуякивать', 'вхуякиваться', 'вхуякнуть',
           'вхуякнуться', 'вхуяривание', 'вхуяривать', 'вхуяриваться', 'вхуярить', 'вхуяриться', 'вхуячивание', 'вхуячивать', 'вхуячиваться',
           'вхуячить', 'вхуячиться', 'вхуяшивать', 'вхуяшиваться', 'вхуяшить', 'вхуяшиться', 'въебать', 'въебаться', 'въебашивать',
           'въебашиваться', 'въебашить', 'въебашиться', 'въебенивать', 'въебениваться', 'въебенить', 'въебениться', 'выблядок', 'выебанный',
           'выебат', 'выебаться', 'высрать', 'высраться', 'выссать', 'выссаться', 'высераться', 'выссереть', 'говнецо', 'говнистый', 'говниться',
           'говно', 'говновоз', 'говнодав', 'говноеб', 'говноед', 'говномес', 'говномер', 'говносерка', 'говнюк', 'голожопая', 'гомик', 'гомосек',
           'гондон', 'гонорея', 'давалка', 'двужопник', 'дерьмо', 'дерьмоед', 'дерьмовый', 'дилдо', 'додрочить', 'додрочиться', 'доебать', 'доебаться',
           'доебенивать', 'доебениваться', 'доебенить', 'доебениться', 'долбоеб', 'допиздить', 'допиздиться', 'допиздовать', 'допиздоваться', 'допиздовывать',
           'допиздовываться', 'допиздохать', 'допиздохаться', 'допиздохивать', 'допиздохиваться', 'допиздошить', 'допиздошиться', 'допиздошивать', 'допиздошиваться',
           'допиздюлить', 'допиздюлиться', 'допиздюливать', 'допиздюливаться', 'допиздюрить', 'допиздюриться', 'допиздюривать', 'допиздюриваться', 'допиздюхать',
           'допиздюхаться', 'допиздюхивать', 'допиздюхиваться', 'допиздякать', 'допиздякаться', 'допиздякивать', 'допиздякиваться',
           'допиздярить', 'допиздяриться', 'допиздяривать', 'допиздяриваться', 'допиздяхать', 'допиздяхаться',
           'допиздяхивать', 'допиздяхиваться', 'допиздячить', 'допиздячиться', 'допиздячивать', 'допиздячиваться',
           'допиздяшить', 'допиздяшиться', 'допиздяшивать', 'допиздяшиваться', 'допиздоболивать', 'допиздоболиваться',
           'допиздоболиться', 'допиздюкать', 'допиздюкаться', 'допиздюкивать', 'допиздюкиваться', 'допизживать',
           'дотрахать', 'дотрахаться', 'дохуйнуть', 'дохуякать', 'дохуякаться', 'дохуякивать', 'дохуякиваться',
           'дохуяривать', 'дохуяриваться', 'дохуярить', 'дохуяриться', 'дохуячить', 'дохуячиться', 'дохуячивать',
           'дохуячиваться', 'дрисня', 'дристать', 'дристун', 'дроченье', 'дрочилыцик', 'дрочить', 'дрочиться', 'дрочка',
           'дрючить', 'дрючиться', 'дурак', 'дуроеб', 'выебать', 'ебало', 'ебальник', 'ебальные', 'ебальный',
           'ебанатик', 'ебанашка', 'ебанутый', 'ебануть', 'ебануться', 'ебать', 'ебат', 'ебаться', 'ебатьс', 'ебитесь',
           'ебло', 'еблом', 'еблысь', 'ебля', 'ебнуть', 'ебнуться', 'ебня', 'ебучий', 'заебла', 'надроченный',
           'объебешь', 'поебать', 'жирнозадый', 'жопа', 'жопой', 'жопастая', 'жопоеб', 'жопенци', 'жопища', 'жопка',
           'жопник', 'жополиз', 'жополизание', 'жопоногий', 'жопочка', 'жопочник', 'жопство', 'жопу', 'забздеть',
           'заблядовать', 'заблядоваться', 'задница', 'задрачивать', 'задрачиваться', 'задроченный', 'задрочить',
           'задрочиться', 'задрючить', 'задрючиться', 'заебанный', 'заебать', 'заебаться', 'заебательская',
           'заебашивать', 'заебашиваться', 'заебашить', 'заебашиться', 'заебенивать', 'заебениваться', 'заебенить',
           'заебениться', 'залупа', 'залупу', 'залупаться', 'залупенить', 'залупень', 'залупить', 'залупляться',
           'залупистый', 'запиздарить', 'запизденная', 'запизденелый', 'запиздить', 'запиздиться', 'запиздоболивать',
           'запиздоболиваться', 'запиздоболить', 'запиздоболиться', 'запиздовать', 'запиздоваться', 'запиздовывать',
           'запиздовываться', 'запиздохать', 'запиздошить', 'запиздошиться', 'запиздошивать', 'запиздошиваться',
           'запиздюкать', 'запиздюкаться', 'запиздюкивать', 'запиздюкиваться', 'запиздюлить', 'запиздюлиться',
           'запиздюливать', 'запиздюливаться', 'запиздюрить', 'запиздюриться', 'запиздюривать', 'запиздюриваться',
           'запиздюхать', 'запиздюхаться', 'запиздюхивать', 'запиздюхиваться', 'запиздючить', 'запиздючиться',
           'запиздючивать', 'запиздючиваться', 'засранец', 'засранка', 'засранный', 'засратый', 'засрать', 'засраться',
           'зассать', 'затраханный', 'затрахать', 'затрахаться', 'затрахивать', 'затрахиваться', 'захуить', 'захуйнуть',
           'захуйнуться', 'захуякать', 'захуякаться', 'захуякивать', 'захуякиваться', 'захуярить', 'захуяриться',
           'захуяривать', 'захуяриваться', 'захуячить', 'захуячиться', 'захуячивать', 'захуячиваться', 'захуяшить',
           'захуяшиться', 'захуяшивать', 'захуяшиваться', 'злоебучий', 'издрочиться', 'измандить', 'измандиться',
           'измандовать', 'измандоваться', 'измандовывать', 'измандовываться', 'изъебать', 'изъебаться', 'изъебашить',
           'изъебашиться', 'изъебашивать', 'изъебашиваться', 'изъебенить', 'изъебениться', 'изъебенивать',
           'изъебениваться', 'изъеб', 'испиздеться', 'испиздить', 'испражнение', 'испражняться', 'исхуякать',
           'исхуякаться', 'исхуякивать', 'исхуякиваться', 'исхуярить', 'исхуяриться', 'исхуяривать', 'какать',
           'какашка', 'кастрат', 'кастрировать', 'клитор', 'клоака', 'кнахт', 'кончить', 'косоебить', 'косоебиться',
           'кривохуй', 'курва', 'курвиный', 'лахудра', 'лох', 'лохудра', 'лохматка', 'манда', 'мандавошка', 'мандавоха',
           'мандить', 'мандиться', 'мандоватая', 'мандовать', 'мандохать', 'мандохаться', 'мандохивать',
           'мандохиваться', 'мандошить', 'мастурбатор', 'минет', 'минетить', 'минетка', 'минетчик', 'минетчица',
           'мозгоеб', 'мозгоебатель', 'мозгоебать', 'мозгоебка', 'мокрожопый', 'мокропиздая', 'моча', 'мочиться',
           'мудак', 'мудашвили', 'мудило', 'мудильщик', 'мудистый', 'мудить', 'мудоеб', 'наебанный', 'наебка',
           'наебщик', 'наебывать', 'наебываться', 'наебыш', 'набздеть', 'наблядоваться', 'надроченный', 'надрочивать',
           'надрочить', 'надрочиться', 'надристать', 'наебать', 'наебаться', 'наебнуть', 'наебнуться', 'накакать',
           'накакаться', 'накакивать', 'напиздить', 'напиздошить', 'напиздюрить', 'напиздюриться', 'насрать',
           'насраться', 'нассать', 'нассаться', 'натрахать', 'натрахаться', 'натрахивать', 'натрахиваться', 'нахуякать',
           'нахуякаться', 'нахуякивать', 'нахуякиваться', 'нахуярить', 'нахуяриться', 'нахуяриться', 'нахуяривать',
           'нахуяриваться', 'нахуячить', 'нахуячиться', 'нахуячивать', 'нахуячиваться', 'нахуяшить', 'недоебанный',
           'недоносок', 'неебущий', 'нищеебство', 'оебыват', 'обдристанный', 'обдристать', 'обдрочиться', 'обосранец',
           'обосранная', 'обосраный', 'обосрать', 'обосраться', 'обоссанец', 'обоссаный', 'обоссать', 'обоссаться',
           'обоссаться', 'обоссывать', 'обоссываться', 'обпиздить', 'обпиздиться', 'обпиздовать', 'обпиздоваться',
           'обпиздовывать', 'обпиздовываться', 'обпиздохать', 'обпиздохаться', 'обпиздохивать', 'обпиздохиваться',
           'обпиздошить', 'обтрахать', 'обтрахаться', 'обтрахивать', 'обтрахиваться', 'обхуярить', 'обхуяриться',
           'обхуячить', 'объебать', 'объебаться', 'объебенить', 'объебнуть', 'объебон', 'одинхуй', 'однапизда',
           'однохуйственно', 'оебать', 'оебашивать', 'оебашить', 'оебенивать', 'оебенить', 'опедерастить', 'опизденеть',
           'опизденный', 'опизденно', 'опиздеть', 'опиздить', 'остоебеть', 'остоебенить', 'остоебенило', 'остопиздеть',
           'остопиздело', 'остохуело', 'остохуеть', 'отдрачивать', 'отдрачиваться', 'отдрочить', 'отдрочиться',
           'отпиздить', 'отпиздошить', 'отпиздяшить', 'отпиздяшиться', 'отпиздяшивание', 'отпиздяшивать',
           'отпиздяшиваться', 'отсасывать', 'отсасываться', 'отсосать', 'отсосаться', 'оттраханная', 'оттрахать',
           'оттрахаться', 'оттрахивать', 'оттрахиваться', 'отхерачить', 'отхуякать', 'отхуякаться', 'отхуякивать',
           'отхуякиваться', 'отхуярить', 'отхуяриться', 'отхуяривать', 'отхуяриваться', 'отхуячить', 'отхуячиться',
           'отхуячивать', 'отхуячиваться', 'отхуяшить', 'отхуяшиться', 'отхуяшивать', 'отхуяшиваться', 'отъебать',
           'отъебывание', 'отъебывать', 'отъебываться', 'отъебашить', 'отъебашивание', 'отъебашивать', 'отъебашиваться',
           'отъебенить', 'отъебениться', 'отъебенивать', 'отъебениваться', 'отъебнуть', 'отьебаться', 'отьебашиться',
           'отьебенивание', 'отьебнуться', 'охуевать', 'охуевающий', 'охуевший', 'охуение', 'охуенно', 'охуенные',
           'охуеть', 'охуительно', 'охуительный', 'охуякать', 'охуякаться', 'охуякивать', 'охуякиваться', 'охуякнуть',
           'охуякнуться', 'охуярить', 'охуяриться', 'охуяривать', 'охуяриваться', 'охуячить', 'охуячиться',
           'охуячивать', 'охуячиваться', 'охуяшить', 'охуяшиться', 'охуяшивать', 'охуяшиваться', 'очко', 'перднуть',
           'падла', 'падлюка', 'педераст', 'педерастина', 'педерастический', 'педерастия', 'педик', 'педрило', 'пежить',
           'пенис', 'пердеж', 'пердеть', 'пердун', 'перебздеть', 'передрачивать', 'передрочить', 'передрочиться',
           'переебаться', 'переебашить', 'перетрахать', 'перетрахаться', 'перетрахивать', 'перетрахиваться',
           'перехуйнуть', 'перехуйнуться', 'перехуякнуть', 'перехуякнуться', 'перехуякать', 'перехуякаться',
           'перехуякивать', 'перехуякиваться', 'перехуярить', 'перехуяриться', 'перехуяривать', 'перехуяриваться',
           'перехуячить', 'перехуячиться', 'перехуячивать', 'пидорас', 'пидор', 'пизда', 'пизданутая', 'пиздануть',
           'пиздануться', 'пиздато', 'пизденка', 'пизденочка', 'пиздень', 'пизденыш', 'пиздеть', 'пиздец', 'пиздища',
           'пиздобол', 'пиздовать', 'пиздолиз', 'пиздомол', 'пиздосос', 'пиздоход', 'пиздуй', 'пиздун', 'пиздюга',
           'пиздюлей', 'пиздюли', 'пиздюлина', 'пиздюк', 'пиздюкать', 'пиздюкаться', 'пиздюшка', 'пиздякать',
           'пиздятина', 'пиздятиной', 'пиздячий', 'писька', 'писюлек', 'плоскозадая', 'поебочка', 'поебывать',
           'поебываться', 'поблудить', 'поблядовать', 'поблядушка', 'подосрать', 'подосраться', 'подоссать',
           'подпиздить', 'подпиздовать', 'подпиздоваться', 'подпиздовывать', 'подпиздовываться', 'подпиздохать',
           'подпиздохаться', 'подпиздохивать', 'подпиздохиваться', 'подпиздошить', 'подпиздошиться', 'подпиздошивать',
           'подпиздякать', 'подпиздякаться', 'подпиздякивать', 'подпиздякиваться', 'подпиздярить', 'подпиздяриться',
           'подпиздяривать', 'подпиздяриваться', 'подпиздяхать', 'подпиздяхаться', 'подпиздяхивать', 'подпиздяхиваться',
           'подпиздячить', 'подпиздячиться', 'подпиздячивать', 'подпиздячиваться', 'подпиздяшить', 'подпиздяшиться',
           'подпиздяшивать', 'подпиздяшиваться', 'подристывать', 'подрочить', 'подсирать', 'подхуякнуть',
           'подхуякнуться', 'подхуякать', 'подхуякаться', 'подхуякивать', 'подхуякиваться', 'подхуярить',
           'подхуяриться', 'подхуяривать', 'подхуяриваться', 'подхуячивать', 'подхуячиться', 'подхуячивать',
           'подхуячиваться', 'подхуяшить', 'подхуяшиться', 'подхуяшивать', 'подхуяшиваться', 'подъеб', 'подъебать',
           'подъебаться', 'подъебашить', 'подъебнуть', 'подъебка', 'подъебывать', 'подъябывать', 'поебанный', 'поебать',
           'поебаться', 'поебень', 'поебистика', 'поебон', 'поебончик', 'попердеть', 'попердеться', 'попердывать',
           'попизденная', 'попиздеть', 'попиздистее', 'попиздить', 'попиздиться', 'попиздоватей', 'попиздоболивать',
           'попиздоболиваться', 'попиздоболить', 'попиздоболиться', 'попиздовать', 'попиздоваться', 'попиздовывать',
           'попиздовываться', 'попиздохать', 'попиздохаться', 'попиздохивать', 'попиздохиваться', 'попиздошить',
           'попиздошиться', 'попиздошивать', 'попиздошиваться', 'попиздюкать', 'попиздюкаться', 'попиздюкивать',
           'попиздюкиваться', 'попиздюлить', 'попиздюлиться', 'попиздюливать', 'попиздюливаться', 'попиздюрить',
           'попиздюриться', 'попиздюривать', 'попиздюриваться', 'попиздюхать', 'попиздюхаться', 'попиздюхивать',
           'попиздюхиваться', 'попиздякать', 'попиздякаться', 'попиздякивать', 'попиздякиваться', 'попиздярить',
           'попиздяриться', 'попиздяривать', 'попиздяриваться', 'попиздяхать', 'попиздяхаться', 'попиздяхивать',
           'попиздяхиваться', 'попиздячить', 'попиздячиться', 'попиздячивать', 'попиздячиваться', 'попиздяшить',
           'попиздяшиться', 'попиздяшивать', 'попиздяшиваться', 'попизживать', 'попизживаться', 'потаскун', 'потаскуха',
           'потраханная', 'потрахать', 'потрахаться', 'потрахивать', 'потрахиваться', 'похер', 'похуист', 'похуякать',
           'похуякаться', 'похуякивать', 'похуякиваться', 'похуярить', 'похуяриться', 'похуяривать', 'похуяриваться',
           'похуячить', 'похуячиться', 'похуячивать', 'похуячиваться', 'похуяшить', 'похуяшиться', 'похуяшивать',
           'похуяшиваться', 'поц', 'пошмариться', 'поябывать', 'приебать', 'приебаться', 'приебывать', 'приебываться',
           'приебашить', 'приебашиться', 'приебашивать', 'приебашиваться', 'приебенить', 'приебениться', 'приебенивать',
           'приебениваться', 'приебехать', 'приебехаться', 'приебехивать', 'приебехиваться', 'приебистый', 'приебурить',
           'приебуриться', 'приебуривать', 'приебуриваться', 'прижопить', 'прижопывать', 'прикинуть', 'примандовать',
           'примандоваться', 'примавдовывать', 'примандовываться', 'примандохать', 'примандохаться', 'примандохивать',
           'примандохиваться', 'примандошить', 'примандошиться', 'примандошивать', 'примандошиваться', 'примандюкать',
           'примандюкаться', 'примандюкивать', 'примандюкиваться', 'примандехать', 'примандехаться', 'примандехивать',
           'примандехиваться', 'примандюлить', 'примандюлиться', 'примандюливать', 'примандюливаться', 'примандюрить',
           'примандюриться', 'примандюривать', 'примандюриваться', 'примандякать', 'примандякаться', 'примандякивать',
           'примандякиваться', 'примандярить', 'примандяриться', 'примандяривать', 'примандяриваться', 'примандяхать',
           'примандяхаться', 'примандяхивать', 'примандяхиваться', 'примандячить', 'примандячиться', 'примандячивать',
           'примандячиваться', 'примандяшить', 'примандяшиться', 'примандяшивать', 'примандяшиваться', 'примудохать',
           'примудохаться', 'примудохивать', 'примудохиваться', 'примандить', 'примандиться', 'припизденный',
           'припиздень', 'припиздить', 'припиздиться', 'припиздывать', 'припиздываться', 'припиздовать',
           'припиздоваться', 'припиздовывать', 'припиздовываться', 'припиздохать', 'припиздохаться', 'припиздохивать',
           'припиздохиваться', 'припиздошить', 'припиздошиться', 'припиздошивать', 'припиздошиваться', 'припиздюкать',
           'припиздюкаться', 'припиздюкивать', 'припиздюкиваться', 'припиздюлить', 'припиздюлиться', 'припиздюливать',
           'припиздюливаться', 'припиздюрить', 'припиздюриться', 'припиздюривать', 'припиздюхать', 'припиздюриваться',
           'припиздюхаться', 'припиздюхивать', 'припиздюхиваться', 'припиздякать', 'припиздякаться', 'припиздякивать',
           'припиздякиваться', 'припиздярить', 'припиздяриться', 'припиздяривать', 'припиздяриваться', 'припиздяхать',
           'припиздяхаться', 'припиздяхивать', 'припиздяхиваться', 'припиздячить', 'припиздячиться', 'припиздячивать',
           'припиздячиваться', 'припиздяшить', 'припиздяшиться', 'припиздяшивать', 'припиздяшиваться', 'припиздронить',
           'припиздрониться', 'припиздронивать', 'припиздрониваться', 'припизживать', 'припизживаться', 'прихуеть',
           'прихуякать', 'прихуякаться', 'прихуякивать', 'прихуякиваться', 'прихуярить', 'прихуяриться', 'прихуяривать',
           'прихуяриваться', 'прихуячить', 'прихуячиться', 'прихуячивать', 'прихуячиваться', 'прихуяшить',
           'прихуяшиться', 'прихуяшивать', 'прихуяшиваться', 'притрахаться', 'проблядовать', 'проблядь', 'проблядушка',
           'продрачивать', 'продрачиваться', 'продрочить', 'продрочиться', 'проебать', 'проебаться', 'проебашить',
           'проебашиться', 'проебашивать', 'проебашиваться', 'проебенить', 'проебениться', 'проебашивать',
           'проебашиваться', 'проебывать', 'проебываться', 'пропиздить', 'пропиздиться', 'пропиздоболивать',
           'пропиздоболиваться', 'пропиздоболить', 'пропиздоболиться', 'пропиздовать', 'пропиздоваться',
           'пропиздовывать', 'пропиздовываться', 'пропиздохать', 'пропиздохаться', 'пропиздохивать', 'пропиздохиваться',
           'пропиздошить', 'пропиздошиться', 'пропиздошивать', 'пропиздошиваться', 'пропиздюкать', 'пропиздюкаться',
           'пропиздюкивать', 'пропиздюкиваться', 'пропиздюлить', 'пропиздюлиться', 'пропиздюливать', 'пропиздюливаться',
           'пропиздюрить', 'пропиздюриться', 'пропиздюривать', 'пропиздюриваться', 'пропиздюхать', 'пропиздюхаться',
           'пропиздюхивать', 'пропиздюхиваться', 'пропиздякать', 'пропиздякаться', 'пропиздякивать', 'пропиздякиваться',
           'пропиздярить', 'пропиздяриться', 'пропиздяривать', 'пропиздяриваться', 'пропиздяхать', 'пропиздяхивать',
           'пропиздяхиваться', 'пропиздячить', 'пропиздячиться', 'пропиздячивать', 'пропиздячиваться', 'пропиздяшить',
           'пропиздяшиться', 'пропиздяшивать', 'пропиздяшиваться', 'пропизживать', 'пропизживаться', 'пропиздон',
           'прохуякать', 'прохуякаться', 'прохуякивать', 'прохуякиваться', 'прохуярить', 'прохуяриться', 'прохуяривать',
           'прохуяриваться', 'прохуячить', 'прохуячиться', 'прохуячивать', 'прохуячиваться', 'прохуяшить',
           'прохуяшиться', 'прохуяшивать', 'прохуяшиваться', 'разблядоваться', 'раздрочить', 'раздрочиться',
           'раззалупаться', 'разнохуйственно', 'разъебать', 'разъебаться', 'разъебашить', 'разъебашиться',
           'разъебашивать', 'разъебашиваться', 'разъебенить', 'разъебениться', 'разъебенивать', 'разъебениваться',
           'распиздить', 'распиздиться', 'распиздовать', 'распиздоваться', 'распиздовывать', 'распиздовываться',
           'распиздохать', 'распиздохаться', 'распиздохивать', 'распиздохиваться', 'распиздошить', 'распиздошиться',
           'распиздошивать', 'распиздошиваться', 'распиздон', 'распиздяй', 'расхуярить', 'расхуяриться', 'расхуяривать',
           'расхуяриваться', 'расхуячить', 'расхуячиться', 'расхуячивать', 'расхуячиваться', 'сдрочить', 'сестроеб',
           'сифилитик', 'сифилюга', 'скурвиться', 'смандить', 'смандиться', 'смандить', 'сперматозавр', 'спиздеть',
           'стерва', 'стервоза', 'сука', 'суки', 'сукин', 'сукины', 'суходрочка', 'суходрочкой', 'сучара', 'сучий',
           'сучка', 'сучье', 'схуякать', 'схуякаться', 'схуякивать', 'схуякиваться', 'схуярить', 'схуяриться',
           'схуяривать', 'схуяриваться', 'схуячить', 'схуячиться', 'схуячивать', 'съебывать', 'съебываться', 'съебать',
           'съебаться', 'съебашить', 'съебашиться', 'съебашивать', 'съебашиваться', 'съебенить', 'съебениться',
           'съебенивать', 'тварь', 'толстожопый', 'толстозадая', 'торчило', 'траханье', 'трахать', 'трахаться',
           'трахнуть', 'трахнуться', 'трепак', 'триппер', 'уебывать', 'уебываться', 'уебыш', 'ублюдок', 'уебать',
           'уебашить', 'уебашивать', 'уебенить', 'уебище', 'усраться', 'усрачка', 'уссать', 'уссаться', 'ухуякать',
           'ухуякаться', 'ухуякивать', 'ухуякиваться', 'ухуярить', 'ухуяриться', 'ухуяривать', 'ухуяриваться',
           'ухуячить', 'ухуячиться', 'ухуячивать', 'ухуячиваться', 'ухуяшить', 'ухуяшиться', 'ухуяшивать',
           'ухуяшиваться', 'фаллос', 'фекал', 'фекалий', 'фекалии', 'хер', 'херами', 'херня', 'херовина', 'херов',
           'хрен', 'хреново', 'хреновое', 'хреновый', 'хуевина', 'хуев', 'хуево', 'хуевый', 'хуек', 'хуечек',
           'худоебина', 'хуебень', 'хуев', 'хуева', 'хуевато', 'хуеватый', 'хуеглот', 'хуегрыз', 'хуедрыга',
           'хуемудрие', 'хуемыслие', 'хуеньки', 'хуеплет', 'хуесос', 'хуета', 'хуетень', 'хуец', 'хуила', 'хуиный',
           'хуистый', 'хуишко', 'хуище', 'хуи', 'хуило', 'хуйло', 'хуй', 'хуйство', 'хуйнуть', 'хуйня', 'хуйню', 'хули',
           'хуюжить', 'хуюжиться', 'хуюживать', 'хуюживаться', 'хуюшки', 'хуя', 'хуяк', 'хуякать', 'хуями', 'хуярить',
           'хуяриться', 'хуястый', 'хуячий', 'хуячить', 'хуячиться', 'хуяшить', 'целка', 'целку', 'целочка',
           'черножопые', 'чернозадый', 'член', 'шалава', 'шлюха', 'шмара', 'шмарить', 'шмариться', 'хуйло', 'отъебись',
           'отьебись', 'спам', 'spam', 'мудила', 'пидарасы', 'чмо', 'дебил', 'нигер', 'гей', 'бичара', 'срака',
            'лгбт', 'лесбиянка', 'трансвистит', 'транс', 'лесбуха', 'обрыган', 'тупорылый', 'тупой', 'чурка',
            'хач', 'пиндос', 'даун', 'гомосек', 'черножоп', 'мудозвон', 'ебобо', 'ебырь', 'терор', 'терорист',
            'заебок', 'заебись', 'ебу', 'ебись', 'спецоперация', 'война', 'убивать', 'хохол', 'хохляндия', 'нищеёб',
            'ёбина', 'украина', 'туз', 'малафья', 'бич', 'дрочила', 'дрочун', 'дцпшник', 'елда', 'писюн', 'сперма', 'ебина',
            'фуфло', 'додик', 'мастурбация', 'фак', 'ваххабит', 'игил', 'фашизм', 'нацизм', 'гитлер'

]

good_list = ['сергей', 'нина']

d =   {'а' : ['а', 'a', '@'],
  'б' : ['б', '6', 'b'],
  'в' : ['в', 'b', 'v'],
  'г' : ['г', 'r', 'g'],
  'д' : ['д', 'd'],
  'е' : ['е', 'e'],
  'ё' : ['ё', 'e'],
  'ж' : ['ж', 'zh', '*'],
  'з' : ['з', '3', 'z'],
  'и' : ['и', 'u', 'i'],
  'й' : ['й', 'u', 'i'],
  'к' : ['к', 'k', 'i{', '|{'],
  'л' : ['л', 'l', 'ji'],
  'м' : ['м', 'm'],
  'н' : ['н', 'h', 'n'],
  'о' : ['о', 'o', '0'],
  'п' : ['п', 'n', 'p'],
  'р' : ['р', 'r', 'p'],
  'с' : ['с', 'c', 's'],
  'т' : ['т', 'm', 't'],
  'у' : ['у', 'y', 'u'],
  'ф' : ['ф', 'f'],
  'х' : ['х', 'x', 'h' , '}{'],
  'ц' : ['ц', 'c', 'u,'],
  'ч' : ['ч', 'ch'],
  'ш' : ['ш', 'sh'],
  'щ' : ['щ', 'sch'],
  'ь' : ['ь', 'b'],
  'ы' : ['ы', 'bi'],
  'ъ' : ['ъ'],
  'э' : ['э', 'e'],
  'ю' : ['ю', 'io'],
  'я' : ['я', 'ya']
}


async def distance(a, b):
    "Calculates the Levenshtein distance between a and b."
    n, m = len(a), len(b)
    if n > m:
        # Make sure n <= m, to use O(min(n, m)) space
        a, b = b, a
        n, m = m, n

    current_row = range(n + 1)  # Keep current and previous row, not entire matrix
    for i in range(1, m + 1):
        previous_row, current_row = current_row, [i] + [0] * n
        for j in range(1, n + 1):
            add, delete, change = previous_row[j] + 1, current_row[j - 1] + 1, previous_row[j - 1]
            if a[j - 1] != b[i - 1]:
                change += 1
            current_row[j] = min(add, delete, change)

    return current_row[n]

async def check_bad_words(name):
    print(name)
    name = name.lower().replace(" ", "")
    name = name.lower().replace("_", "")
    print(name)
    for key, value in d.items():
        #Проходимся по каждой букве в значении словаря. То есть по вот этим спискам ['а', 'a', '@'].
        for letter in value:
            #Проходимся по каждой букве в нашей фразе.
            for phr in name:
                #Если буква совпадает с буквой в нашем списке.
                if letter == phr:
                    #Заменяем эту букву на ключ словаря.
                    name = name.replace(phr, key)

    data = True
    #Проходимся по всем словам.
    for word in bad_list:
        #Разбиваем слово на части, и проходимся по ним.
        for part in range(len(name)):
            #Вот сам наш фрагмент.
            fragment = name[part: part+len(word)]
            #Если отличие этого фрагмента меньше или равно 25% этого слова, то считаем, что они равны.
            if await distance(fragment, word) <= len(word)*0.25:
                #Если они равны, выводим надпись о их нахождении.
                print("Найдено", word, "\nПохоже на", fragment)
                data = False

    return data